server:
  port: 9999

spring:
  mvc:
    servlet:
      load-on-startup=1:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///htgx1dz
  redis:
    port: 6379
    host: localhost
logging:
  level:
    com.dz: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.dz.*.entity


